apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- qbittorrent-config.yaml
- qbittorrent-secret.yaml

images:
- name: controller
  newName: ghcr.io/guidonguido/qbittorrent-operator
  newTag: v0.1.6

